FROM golang:1.10 AS builder

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

ADD . /go/src/github.com/Vinubaba/SANTC-API
WORKDIR /go/src/github.com/Vinubaba/SANTC-API
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure -vendor-only
WORKDIR /go/src/github.com/Vinubaba/SANTC-API/event-manager
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -a -installsuffix cgo -i -o /go/bin/event-manager

FROM alpine
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/event-manager /go/bin/event-manager
COPY --from=builder /go/src/github.com/Vinubaba/SANTC-API/event-manager/sql /go/migrations/sql

ENTRYPOINT ["/go/bin/event-manager"]